#!/bin/bash

# Various way to print all the lines till the end of the file after a specific match


sed -n '/>>>>---------------------------------- (lcqo) ----------------------------------/,$p' 5_well_no_overlap.log.0 
# sed -n '/>>>>---------------------------------- (lcqo) ----------------------------------/,$p' | sed '1d' 5_well_no_overlap.log.0 > risultato.txt
# sed -n '/Solve time/,$p' | tail -n +2 5_well_no_overlap.log.0
# sed -e '1,/>>>>---------------------------------- (lcqo) ----------------------------------/d' 5_well_no_overlap.log.0
# sed -n '/^>>>>---------------------------------- (lcqo) ----------------------------------$/ { :a; n; p; ba; }' 5_well_no_overlap.log.0
>>>>---------------------------------- (MQW) -----------------------------------


sed -n '/>>>>---------------------------------- (lcqo) ----------------------------------/,$p' 5_well_no_overlap.log.0 > risultato.txt
